ECHO OFF
ECHO 'PARTITIONING DISK'
DISKPART /S INSTALLRT.TXT
ECHO 'INSTALLING RT'
DISM /APPLY-IMAGE /IMAGEFILE:D:\SOURCES\INSTALL.WIM /INDEX:1 /APPLYDIR:C:\
ECHO 'COPYING EFI'
MOUNTVOL S: /S
XCOPY /S D:\EFIESP\* S:\
ECHO 'FIXING BOOT ENTRIES'
BOOTREC /FIXBOOT
BOOTREC /REBUILDBCD
EXIT
