ECHO OFF
ECHO 'BEFORE CONTINUING, VERIFY THAT ALL BITLOCKERS ARE TURNED OFF AND USB DRIVE LETTER IS D'
set /p CONFIRM_CONTINUE=CONFIRM READY FOR INSTALL [y/n]?:

IF /I "%CONFIRM_CONTINUE%"=="n" GOTO EOF
IF /I "%CONFIRM_CONTINUE%"=="N" GOTO EOF

:MENU
ECHO 'GOOD, LETS BEGIN'
ECHO '0) EXIT'
ECHO '1) PARTITION DISK'
ECHO '2) INSTALL WINRT'
ECHO '3) COPY ESPEFI'
ECHO '4) COPY EFI'
ECHO '5) COPY GRUB'
ECHO '6) FIXBOOT'
ECHO '7) SECUREBOOT'
set /p ID=ENTER ACTION:
ECHO ID
IF "%ID%"=="0" EXIT
IF "%ID%"=="1" GOTO PARTITIONING
IF "%ID%"=="2" GOTO INSTALLWNRT
IF "%ID%"=="3" GOTO ESPEFI
IF "%ID%"=="4" GOTO EFI
IF "%ID%"=="5" GOTO GRUB
IF "%ID%"=="6" GOTO FIXBOOT
IF "%ID%"=="7" GOTO SECUREBOOT
IF %ID% GOTO MENU

:PARTITIONING
ECHO 'PARTITIONING DISK, THIS MIGHT TAKE A WHILE...'
DISKPART /S INSTALLRT.TXT
ECHO 'PARTITIONING DISK COMPLETE'
GOTO MENU

:INSTALLWNRT
ECHO 'INSTALLING RT'
DISM /APPLY-IMAGE /IMAGEFILE:D:\SOURCES\INSTALL.WIM /INDEX:1 /APPLYDIR:C:\
ECHO 'WINRT 8.0 INSTALL FINISHED'
GOTO MENU

:ESPEFI
ECHO 'COPYING ESPEFI'
CALL ESPEFI.CMD
GOTO MENU

:EFI
ECHO 'COPYING EFI'
CALL EFI.CMD
GOTO MENU

:FIXBOOT
ECHO 'FIXING BOOT ENTRIES'
BOOTREC /FIXBOOT
BOOTREC /REBUILDBCD
GOTO MENU

:SECUREBOOT
ECHO 'EXECUTING SECUREBOOT WORKAROUND'
CALL SECUREBOOT.CMD
GOTO MENU

:GRUB
ECHO 'COPYING GRUB'
CALL GRUB.CMD
GOTO MENU
