ECHO OFF
ECHO 'BEFORE CONTINUING, VERIFY THAT ALL BITLOCKERS ARE TURNED OFF AND USB DRIVE LETTER IS D'
set /p CONFIRM_CONTINUE=CONFIRM READY FOR INSTALL [y/n]?:

IF /I "%CONFIRM_CONTINUE%"=="n" GOTO EOF
IF /I "%CONFIRM_CONTINUE%"=="N" GOTO EOF

ECHO 'PARTITIONING DISK, THIS MIGHT TAKE A WHILE...'
DISKPART /S INSTALLRT.TXT
ECHO 'PARTITIONING DISK COMPLETE'

ECHO 'INSTALLING MINIMAL BOOT'
DISM /APPLY-IMAGE /IMAGEFILE:D:\SOURCES\BOOT.WIM /INDEX:1 /APPLYDIR:C:\
ECHO 'MINIMAL BOOT INSTALL FINISHED'

ECHO 'COPYING EFI'
CALL EFI.CMD

ECHO 'FIXING BOOT ENTRIES'
BOOTREC /FIXBOOT
BOOTREC /REBUILDBCD

ECHO 'EXECUTING SECUREBOOT WORKAROUND'
CALL SECUREBOOT.CMD

ECHO 'PLEASE REBOOT'

EXIT
